import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { Footer, HeroSection, ProducctsSection } from "../components";
import Layout from "../components/Layout";
import { saveProductToRedux } from "../store/slices/productSlice";
export default function Home({ products }) {
  const dispatch = useDispatch();
  useEffect(() => {
    if (products.length) {
      dispatch(saveProductToRedux(products));
    }
  }, []);
  return (
    <>
      <Head>
        <title>Ecom NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen overflow-auto">
        <Layout>
          <HeroSection />
          {/* <input
            value={phrase}
            onChange={(e) => setPhrase(e.target.value)}
            type="text"
            placeholder="Search for products..."
            className="bg-gray-200 w-full py-2 px-4 rounded-xl"
          /> */}
          <ProducctsSection products={products} />
          <Footer />
        </Layout>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (response) => response.json()
  );

  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    },
  };
}
